name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag $DOCKER_USERNAME/elevation-server:$(date +%s)
    - name: Login to Docker
      run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - name: Publish Docker image
      run: docker push $DOCKER_USERNAME/elevation-server
