name: Docker Image CI

on:
  push:
    branches:
      - master

jobs:
  publish-to-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{ secrets.DockerUsername }}/elevation-server

      - name: Start the Docker container
        run: docker run -d -p 3000:3000 ${{ secrets.DockerUsername }}/elevation-server

      - name: Integration test the Docker container
        run: test/integration-test.sh

      - name: Login to Docker
        run: echo "${{ secrets.DockerPassword }}" | docker login -u "${{ secrets.DockerUsername }}" --password-stdin

      - name: Publish Docker image
        run: docker push ${{ secrets.DockerUsername }}/elevation-server
