name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ secrets.DockerUsername }}/elevation-server:$(date +%s)
    - name: Login to Docker
      run: echo "${{ secrets.DockerPassword }}" | docker login -u "${{ secrets.DockerUsername }}" --password-stdin
    - name: Publish Docker image
      run: docker push ${{ secrets.DockerUsername }}/elevation-server
