name: Docker Image CI

on:
  push:
    branches:
      - master

jobs:
  publish-to-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build multi-platform Docker image
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --tag ${{ secrets.DockerUsername }}/elevation-server \
            --file Dockerfile \
            --load \
            .

      - name: Start the Docker container
        run: docker compose build && docker compose up -d

      - name: Wait for the Docker container to start up
        run: sleep 10

      - id: test
        name: Integration test the Docker container
        run: test/integration-test.sh

      - name: Dump container logs
        if: failure() && steps.test.outcome == 'failure'
        run: |
          docker compose logs app

      - name: Login to Docker
        run: echo "${{ secrets.DockerPassword }}" | docker login -u "${{ secrets.DockerUsername }}" --password-stdin

      - name: Publish Docker image
        run: docker push ${{ secrets.DockerUsername }}/elevation-server
